from crewai.tools import tool
from pptx import Presentation
from pptx.util import Inches

@tool("PPT Generator")
def generate_ppt(presentation_data: dict) -> str:
    """
    Generates a PowerPoint presentation based on the provided data.
    The input 'presentation_data' should be a dictionary containing:
    - 'title': The title of the presentation (str).
    - 'slides': A list of dictionaries, where each dictionary represents a slide
                and can contain 'title', 'content', 'image_path'.
    """
    prs = Presentation()

    # Add title slide
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    title = slide.shapes.title
    subtitle = slide.placeholders[1]
    title.text = presentation_data.get("title", "Untitled Presentation")
    subtitle.text = "Generated by CrewAI"

    # Add content slides
    for slide_data in presentation_data.get("slides", []):
        bullet_slide_layout = prs.slide_layouts[1]
        slide = prs.slides.add_slide(bullet_slide_layout)
        title = slide.shapes.title
        body = slide.shapes.placeholders[1]

        if "title" in slide_data:
            title.text = slide_data["title"]
        if "content" in slide_data:
            tf = body.text_frame
            tf.clear()  # Clear existing text
            for paragraph in slide_data["content"].split('\n'):
                p = tf.add_paragraph()
                p.text = paragraph

        if "image_path" in slide_data:
            left = top = Inches(1)
            slide.shapes.add_picture(slide_data["image_path"], left, top, width=Inches(6))

    output_filename = "generated_presentation.pptx"
    prs.save(output_filename)
    return f"PowerPoint presentation '{output_filename}' generated successfully."